### ISSUE TITLE
Incompatibility with Python 3.5 (Ubuntu 16.04 and derivates)

### ISSUE THREAD

**Issue by Znuff** [gentoo-root/certbot-dns-henet#2]
Ubuntu 16.04 ships with Python 3.5.2.

Unfortunately, Literal String Interpolations (`f'string{variable}'` - or simply "f-strings")  were added in [PEP-498](https://www.python.org/dev/peps/pep-0498/), in Python 3.6.

Thus, trying to run this on Ubuntu 16.04 will raise a Syntax Error exception:

	$ python3 setup.py test
	running test
	running egg_info
	writing dependency_links to certbot_dns_henet.egg-info/dependency_links.txt
	writing requirements to certbot_dns_henet.egg-info/requires.txt
	writing entry points to certbot_dns_henet.egg-info/entry_points.txt
	writing certbot_dns_henet.egg-info/PKG-INFO
	writing top-level names to certbot_dns_henet.egg-info/top_level.txt
	reading manifest file 'certbot_dns_henet.egg-info/SOURCES.txt'
	writing manifest file 'certbot_dns_henet.egg-info/SOURCES.txt'
	running build_ext
	Traceback (most recent call last):
	  File "setup.py", line 42, in <module>
		'dns-henet = certbot_dns_henet.dns_henet:Authenticator',
	  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
		dist.run_commands()
	  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
		self.run_command(cmd)
	  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
		cmd_obj.run()
	  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 211, in run
		self.run_tests()
	  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 234, in run_tests
		**exit_kwarg
	  File "/usr/lib/python3.5/unittest/main.py", line 93, in __init__
		self.parseArgs(argv)
	  File "/usr/lib/python3.5/unittest/main.py", line 123, in parseArgs
		self._do_discovery([])
	  File "/usr/lib/python3.5/unittest/main.py", line 228, in _do_discovery
		self.test = loader.discover(self.start, self.pattern, self.top)
	  File "/usr/lib/python3.5/unittest/loader.py", line 341, in discover
		tests = list(self._find_tests(start_dir, pattern))
	  File "/usr/lib/python3.5/unittest/loader.py", line 398, in _find_tests
		full_path, pattern, namespace)
	  File "/usr/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
		tests = self.loadTestsFromModule(package, pattern=pattern)
	  File "/usr/lib/python3/dist-packages/setuptools/command/test.py", line 43, in loadTestsFromModule
		tests.append(self.loadTestsFromName(submodule))
	  File "/usr/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
		module = __import__(module_name)
	  File "/home/user/certbot-dns-henet/certbot_dns_henet/dns_henet.py", line 119
		_logger.error(f'Failed to remove the Record with id={record_id}.')
																		^
	SyntaxError: invalid syntax

# Solution

## Fix the plugin
Someone needs to submit a patch to change "f-strings" to older string formatting methods like `%-formatting`, `str.format` or `str.format`

## Update the Python on the OS

Install a newer Python version via PPA for Ubuntu 16.04, like from the [Deadsnakes PPA](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa). Here I installed 3.7:

	sudo add-apt-repository ppa:deadsnakes/ppa
	sudo apt-get update
	sudo apt-get install python3.7 python3.7-dev

	# setup alternatives properly, so we can revert to 3.5 in case we encounter issues 
	sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1
	sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2
	update-alternatives --config python3 # select 3.7

	sudo pip3 install -U setuptools beautifulsoup4 cryptography # we need the compatible packages

This might leave you with a broken Python3 on your system, so be very careful

**Comment by gentoo-root** [comment]
Yes, this is expected: if you look at setup.py, you'll see that the minimum supported version is declared to be 3.7. This is because in order to support 3.5, I have to test with that version, and I simply don't have it, so I developed for the version that I have.

However, I realize that it is important to support older versions, too, because there are LTS server distributions, and certbot itself supports a wide range of Python versions. So, your report can be a valid feature request.

The changes required to support Python 3.5 should me minimal, but I'll have to find some time to install the old Python and test it.

There is an interesting [project](https://github.com/asottile/future-fstrings/) that backports support for f-strings to older versions, but I would prefer just the good old `.format()` to avoid having an external dependency that is not really needed and to avoid slowdown in parsing.

BTW, I don't recommend doing this: `sudo pip3 install -U setuptools beautifulsoup4 cryptography`, as it'll write directly to /usr/lib/python3.7, and the locations under /usr (in contrast to /usr/local) are managed by the package manager. It can cause conflicts. There are several options that are better:

- installing the dependencies from the package manager;
- using venv or virtualenv;
- installing to a user-specific directory (`pip install --user`);
- installing to /usr/local/lib/python3.7/site-packages and adding it to PYTHONPATH.

**Comment by Znuff** [comment]
`pip` writes to `/usr/local/python<version>`, it never touches `/usr/lib/python<version>`, for example:

	# pip3 install -U idna
	Collecting idna
	  Downloading https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl (58kB)
		100% |████████████████████████████████| 61kB 752kB/s
	Installing collected packages: idna
	  Found existing installation: idna 2.5
		Not uninstalling idna at /usr/lib/python3/dist-packages, outside environment /usr
	Successfully installed idna-2.8

**Comment by gentoo-root** [comment]
>pip writes to /usr/local/python<version>, it never touches /usr/lib/python<version>

No, upstream pip installs directly to /usr. Your distribution may have patched pip to install to /usr/local, but it's not the case for all distributions. BTW, your example doesn't prove your point.
